### ISSUE TITLE
Fix Feature Engineering module Taxi Fare data mismatch

### ISSUE THREAD

**Issue by takumiohym** [GoogleCloudPlatform/asl-ml-immersion#192]
Code and Data is different in [4_keras_adv_feat_eng.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb) lab.

https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/506ef9bea018149a3714f643ea49711a090752f6/notebooks/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb?short_path=8c5445b#L99-L107

Data
![Screen Shot 2022-04-15 at 11 46 50](https://user-images.githubusercontent.com/6895245/163510097-30829dfb-2e70-4d1e-b8b7-6b680ed9728d.png)

**Comment by sanjanalreddy** [comment]
@takumiohym I agree that the order of the CSV_COLUMNS and the taxi-train.csv don't match. But since the [taxi-train.csv](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/feature_engineering/data/taxi-train.csv) file in the feature_engineering folder has column names, my suggestion is to just re-order the CSV_COLUMNS variable accordingly and not change the training file. 

The training file from `introduction_to_tensorflow` has only 7332 rows whereas the one in the `feature_engineerin` folder has 53K+ rows. It is better to train with more data rather than repeat the small dataset of 7332 rows 30 times.

**Comment by takumiohym** [comment]
Thanks!
Actually this is not only about the order but the column itself is different ( hourofday and dayofweek)
Basically I just copied the same file from the introduction_to_tensorflow directory, and I thought it would be good to stick with the same dataset to compare the performance with/without feature engineering. (And it works very well despite its size!)

**Comment by sanjanalreddy** [comment]
I see! 

The only columns which we need for training are fare_amount, pickup_longitude, pickup_latitude, dropoff_longitude, drop_off_lattitude and passenger_count. We actually do `del transformed['pickup_datetime']` later so the pickup_datetime does not matter. So we could also just chose these columns from the larger dataset and re-write the original train file and potentially also copy this to the feature_engineering folder. This will avoid the having to use the *30 multiplier.

But, if you think the performance is good enough and the continuity of the data will tell a good story I am good with that too.

**Comment by takumiohym** [comment]
Thanks Sanjana :)
